### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by yutkat** [high-moctane/nextword#1]
Thanks for making a useful application!

By the way, I want to release the binary because I don't want to compile.
I think many other Go apps do it.
https://github.com/cli/cli/releases

**Comment by high-moctane** [comment]
Hello @yutakatay, thank you for your suggestion.

I introduced gorelease-action for automatic build when the new tag is pushed.
Could you visit [Releases](https://github.com/high-moctane/nextword/releases) page and check the binary works?

**Comment by yutkat** [comment]
I checked it. It worked!

I appreciate your fantastic job :smile:
